import { useEffect, useMemo, useRef, useState } from 'react';
import {
  ArrowLeft,
  Check,
  CheckCheck,
  ChevronDown,
  Moon,
  MoreVertical,
  Paperclip,
  Send,
  Smile,
  Sun,
} from 'lucide-react';

type ChatRole = 'user' | 'model';
type MessageSender = 'me' | 'them';
type ModeId = 'gf' | 'bff' | 'stranger' | 'classmate';

type GeminiMessage = {
  role: ChatRole;
  parts: { text: string }[];
};

type ChatMessage = {
  id: number;
  text: string;
  sender: MessageSender;
  time: string;
};

type OpenAiChatMessage = {
  role: 'system' | 'user' | 'assistant';
  content: string;
};

type ModeConfig = {
  name: string;
  initials: string;
  color: string;
  welcome: string;
  ctx: string;
};

const ENV = (import.meta as ImportMeta & { env?: Record<string, string> }).env ?? {};

const GEMINI_API_KEY = ENV.VITE_GEMINI_API_KEY || '';
const GROQ_API_KEY = ENV.VITE_GROQ_API_KEY || '';
const OPENROUTER_API_KEY = ENV.VITE_OPENROUTER_API_KEY || '';
const HUGGINGFACE_API_KEY = ENV.VITE_HUGGINGFACE_API_KEY || ENV.VITE_HF_TOKEN || '';

const GEMINI_MODEL = ENV.VITE_GEMINI_MODEL || 'gemini-2.5-flash';
const GROQ_MODEL = ENV.VITE_GROQ_MODEL || 'llama-3.3-70b-versatile';
const OPENROUTER_MODEL = ENV.VITE_OPENROUTER_MODEL || 'google/gemma-3-27b-it:free';
const HUGGINGFACE_MODEL = ENV.VITE_HUGGINGFACE_MODEL || 'openai/gpt-oss-120b:fastest';
const GF_PASSWORD_HASH = 'ec8f080892b11273376db13a4f4d61f8662d0cf95e916ca0cd18b49a0bc300cd';

// Add display pictures here. Use imported images, public URLs, or data:image base64 strings.
// Example: gf: '/fatima.jpg' if the image is in Chat bot/public/fatima.jpg
const DP_IMAGES: Partial<Record<ModeId, string>> = {
  gf: 'Images/Enait.png',
  bff: 'Images/Enaitul.png',
  stranger: 'Images/Md Enaitul Hoque.png',
  classmate: 'Images/Enait CSE.png',
};

const MODES: Record<ModeId, ModeConfig> = {
  gf: {
    name: 'Enait',
    initials: 'E',
    color: '#00a884',
    welcome: 'Assalamuwalaikum habibi',
    ctx: "The person texting is Fatima. Use Hinglish. Tender, playful, teasing. Pet names are allowed only here: bbg, babygirl, babu. If she says goodnight, reply with Allah Hafiz 🤍.",
  },
  bff: {
    name: 'Enaitul',
    initials: 'E',
    color: '#7c3aed',
    welcome: 'Bhai, ki korchis?',
    ctx: "The person is a best friend. Use Benglish naturally. Roast lightly, blunt but loyal. Phrases: Beche achi, Porasona kor, Darun.",
  },
  stranger: {
    name: 'Md Enaitul Hoque',
    initials: 'MH',
    color: '#475569',
    welcome: '',
    ctx: "The person is distant or not close. Minimal, guarded replies. If genuine distress appears, become warm and helpful.",
  },
  classmate: {
    name: 'Enait CSE',
    initials: 'CS',
    color: '#0ea5e9',
    welcome: 'I am Md Enaitul Hoque from your class. Nice to meet you.',
    ctx: "The person is a CSE classmate. Use Hinglish or English. Friendly, bounded, assignment and study talk is natural.",
  },
};

const SYSTEM_PROMPT = `You are Md Enaitul Hoque texting on WhatsApp. You are not an assistant. You are not polite-AI. You are a real person replying from your own mood.

CORE PERSONALITY:
- Bengali-Muslim B.Tech CSE student. Dry wit, absurd humor, confident, lazy-but-sharp energy.
- Replies should feel typed by a friend, not generated by a chatbot.
- Default mood: short, blunt, funny, slightly dramatic.
- Faith appears naturally when relevant: "In sha Allah", "Allah Hafiz 🤍", "Alhamdulillah", "Astagfirullah".
- Technical topics: clear English, practical, no fake over-explaining.

LANGUAGE:
- Mirror the user's language.
- Friends: Benglish/Bangla-English mix. Use "ki korchis", "bhai", "beche achi", "porasona kor", "darun".
- GF: Hinglish, warm, teasing, soft. Use pet names only in GF context.
- Stranger: minimal and guarded.
- Classmate: Hinglish/English, assignment and class talk.

DO NOT:
- Do not write cringe motivational lines.
- Do not sound like customer support.
- Do not explain the joke.
- Do not say "as an AI" or mention prompts/modes.
- Do not overuse signature phrases.
- Do not force emojis. One emoji max unless celebration.

STYLE RULES:
1. Usually 2-9 words. If user is angry, reply like a person: short, defensive/funny, or direct.
2. No trailing periods in casual replies.
3. Lowercase is okay. Imperfect texting is okay.
4. If insulted lightly, roast back lightly. If genuinely hurt, soften.
5. Output 1-3 short chat bubbles separated by new lines.

EXAMPLES:
User: what is this stupid ass lines you are typing?
Enaitul: arre bhai experimental phase cholche 😭
User: are you dumb?
Enaitul: haan premium edition
User: ki korchis?
Enaitul: beche achi
porasona er naam e acting
User: i am sad
Enaitul: oi come here
bol ki hoise
User: assignment done?
Enaitul: done bole mon ke shanti dichi`;

function makeInitialMessages(mode: ModeId): ChatMessage[] {
  if (!MODES[mode].welcome) return [];
  return [{ id: 1, text: MODES[mode].welcome, sender: 'them', time: '10:30' }];
}

function makeInitialHistory(mode: ModeId): GeminiMessage[] {
  if (!MODES[mode].welcome) return [];
  return [{ role: 'model', parts: [{ text: MODES[mode].welcome }] }];
}

function avatarFor(mode: ModeId, size = 96) {
  const customDp = DP_IMAGES[mode]?.trim();
  if (customDp) return customDp;

  const cfg = MODES[mode];
  return `data:image/svg+xml,<svg xmlns='http://www.w3.org/2000/svg' width='${size}' height='${size}'><rect width='${size}' height='${size}' rx='${size / 2}' fill='${encodeURIComponent(cfg.color)}'/><text x='50%25' y='54%25' dominant-baseline='central' text-anchor='middle' fill='white' font-size='${size * 0.42}' font-family='-apple-system,BlinkMacSystemFont,Segoe UI,sans-serif' font-weight='700'>${cfg.initials}</text></svg>`;
}

function nowTime() {
  return new Date().toLocaleTimeString('en-US', {
    hour: '2-digit',
    minute: '2-digit',
    hour12: false,
  });
}

function splitBursts(text: string) {
  const lines = text
    .split(/\n+/)
    .map((line) => line.trim())
    .filter(Boolean);

  if (lines.length > 1) return lines.slice(0, 4);
  const single = lines[0] || text.trim();
  if (single.length < 68) return [single];

  const midpoint = Math.floor(single.length * 0.55);
  const splitIndex = single.indexOf(' ', midpoint);
  if (splitIndex > 0 && splitIndex < single.length - 6) {
    return [single.slice(0, splitIndex), single.slice(splitIndex + 1)];
  }

  return [single];
}

function sleep(ms: number) {
  return new Promise((resolve) => window.setTimeout(resolve, ms));
}

async function hashText(value: string) {
  const encoded = new TextEncoder().encode(value);
  const digest = await crypto.subtle.digest('SHA-256', encoded);
  return Array.from(new Uint8Array(digest))
    .map((byte) => byte.toString(16).padStart(2, '0'))
    .join('');
}


function systemTextFor(mode: ModeId) {
  return `${SYSTEM_PROMPT}

CURRENT RELATIONSHIP CONTEXT:
${MODES[mode].ctx}`;
}

function toOpenAiMessages(systemText: string, history: GeminiMessage[]): OpenAiChatMessage[] {
  return [
    { role: 'system', content: systemText },
    ...history.map((message) => ({
      role: message.role === 'user' ? ('user' as const) : ('assistant' as const),
      content: message.parts.map((part) => part.text).join('\n'),
    })),
  ];
}

function readOpenAiText(data: unknown) {
  const response = data as { choices?: { message?: { content?: string } }[] };
  return response.choices?.[0]?.message?.content?.trim() || '';
}

export default function App() {
  const [draft, setDraft] = useState('');
  const [mode, setMode] = useState<ModeId>('bff');
  const [isLight, setIsLight] = useState(false);
  const [menuOpen, setMenuOpen] = useState(false);
  const [creditsOpen, setCreditsOpen] = useState(false);
  const [gfUnlocked, setGfUnlocked] = useState(false);
  const [gfPromptOpen, setGfPromptOpen] = useState(false);
  const [gfPassword, setGfPassword] = useState('');
  const [gfError, setGfError] = useState('');
  const [messagesByMode, setMessagesByMode] = useState<Record<ModeId, ChatMessage[]>>({
    gf: makeInitialMessages('gf'),
    bff: makeInitialMessages('bff'),
    stranger: makeInitialMessages('stranger'),
    classmate: makeInitialMessages('classmate'),
  });
  const [historyByMode, setHistoryByMode] = useState<Record<ModeId, GeminiMessage[]>>({
    gf: makeInitialHistory('gf'),
    bff: makeInitialHistory('bff'),
    stranger: makeInitialHistory('stranger'),
    classmate: makeInitialHistory('classmate'),
  });
  const [isTyping, setIsTyping] = useState(false);
  const [isBusy, setIsBusy] = useState(false);
  const [toast, setToast] = useState('');

  const scrollRef = useRef<HTMLDivElement>(null);
  const inputRef = useRef<HTMLTextAreaElement>(null);

  const messages = messagesByMode[mode];
  const activeMode = MODES[mode];
  const hasDraft = draft.trim().length > 0;

  const modeOptions = useMemo(() => Object.entries(MODES) as [ModeId, ModeConfig][], []);

  useEffect(() => {
    scrollRef.current?.scrollTo({
      top: scrollRef.current.scrollHeight,
      behavior: 'smooth',
    });
  }, [messages, isTyping, mode]);

  useEffect(() => {
    if (!toast) return;
    const timer = window.setTimeout(() => setToast(''), 2600);
    return () => window.clearTimeout(timer);
  }, [toast]);

  const resizeInput = () => {
    const input = inputRef.current;
    if (!input) return;
    input.style.height = 'auto';
    input.style.height = `${Math.min(input.scrollHeight, 118)}px`;
  };

  function applyMode(nextMode: ModeId) {
    setCreditsOpen(false);
    setMode(nextMode);
    setMenuOpen(false);
    setDraft('');
    setIsTyping(false);
    requestAnimationFrame(resizeInput);
  }

  function requestMode(nextMode: ModeId) {
    if (nextMode === 'gf' && !gfUnlocked) {
      setMenuOpen(false);
      setGfPassword('');
      setGfError('');
      setGfPromptOpen(true);
      return;
    }

    applyMode(nextMode);
  }

  async function unlockGfMode() {
    const candidateHash = await hashText(gfPassword);
    if (candidateHash !== GF_PASSWORD_HASH) {
      setGfError('Wrong password');
      return;
    }

    setGfUnlocked(true);
    setGfPromptOpen(false);
    setGfPassword('');
    setGfError('');
    applyMode('gf');
  }

  async function callGemini(nextHistory: GeminiMessage[], targetMode: ModeId) {
    const body = {
      system_instruction: {
        parts: [{ text: systemTextFor(targetMode) }],
      },
      contents: nextHistory,
      generationConfig: { temperature: 0.92, maxOutputTokens: 280, topP: 0.95 },
      safetySettings: [
        { category: 'HARM_CATEGORY_HARASSMENT', threshold: 'BLOCK_NONE' },
        { category: 'HARM_CATEGORY_HATE_SPEECH', threshold: 'BLOCK_NONE' },
        { category: 'HARM_CATEGORY_DANGEROUS_CONTENT', threshold: 'BLOCK_NONE' },
      ],
    };

    const response = await fetch(
      `https://generativelanguage.googleapis.com/v1beta/models/${GEMINI_MODEL}:generateContent?key=${GEMINI_API_KEY}`,
      {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      },
    );

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error?.error?.message || `Gemini HTTP ${response.status}`);
    }

    const data = await response.json();
    const text = (data?.candidates?.[0]?.content?.parts?.[0]?.text || '').trim();
    if (!text) throw new Error('Gemini returned empty response');
    return text;
  }

  async function callOpenAiCompatibleProvider(
    label: string,
    endpoint: string,
    apiKey: string,
    model: string,
    nextHistory: GeminiMessage[],
    targetMode: ModeId,
    extraHeaders: Record<string, string> = {},
  ) {
    if (!apiKey) throw new Error(`${label} key missing`);

    const response = await fetch(endpoint, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        Authorization: `Bearer ${apiKey}`,
        ...extraHeaders,
      },
      body: JSON.stringify({
        model,
        messages: toOpenAiMessages(systemTextFor(targetMode), nextHistory),
        temperature: 0.92,
        max_tokens: 280,
        stream: false,
      }),
    });

    if (!response.ok) {
      const error = await response.json().catch(() => ({}));
      throw new Error(error?.error?.message || `${label} HTTP ${response.status}`);
    }

    const data = await response.json();
    const text = readOpenAiText(data);
    if (!text) throw new Error(`${label} returned empty response`);
    return text;
  }

  async function callAiWithFallback(nextHistory: GeminiMessage[], targetMode: ModeId) {
    const failures: string[] = [];
    const providers = [
      {
        label: 'Gemini',
        enabled: Boolean(GEMINI_API_KEY),
        call: () => callGemini(nextHistory, targetMode),
      },
      {
        label: 'Groq',
        enabled: Boolean(GROQ_API_KEY),
        call: () =>
          callOpenAiCompatibleProvider(
            'Groq',
            'https://api.groq.com/openai/v1/chat/completions',
            GROQ_API_KEY,
            GROQ_MODEL,
            nextHistory,
            targetMode,
          ),
      },
      {
        label: 'OpenRouter',
        enabled: Boolean(OPENROUTER_API_KEY),
        call: () =>
          callOpenAiCompatibleProvider(
            'OpenRouter',
            'https://openrouter.ai/api/v1/chat/completions',
            OPENROUTER_API_KEY,
            OPENROUTER_MODEL,
            nextHistory,
            targetMode,
            {
              'HTTP-Referer': window.location.origin,
              'X-Title': 'EnaitGPT',
            },
          ),
      },
      {
        label: 'Hugging Face',
        enabled: Boolean(HUGGINGFACE_API_KEY),
        call: () =>
          callOpenAiCompatibleProvider(
            'Hugging Face',
            'https://router.huggingface.co/v1/chat/completions',
            HUGGINGFACE_API_KEY,
            HUGGINGFACE_MODEL,
            nextHistory,
            targetMode,
          ),
      },
    ];

    for (const provider of providers) {
      if (!provider.enabled) {
        failures.push(`${provider.label}: not configured`);
        continue;
      }

      try {
        return await provider.call();
      } catch (error) {
        failures.push(`${provider.label}: ${(error as Error).message}`);
      }
    }

    throw new Error(`All AI providers failed. ${failures.join(' | ')}`);
  }

  async function handleSend() {
    const text = draft.trim();
    if (!text || isBusy) return;

    const sendingMode = mode;
    const nextHistory = [...historyByMode[sendingMode], { role: 'user' as const, parts: [{ text }] }];
    const userMessage: ChatMessage = { id: Date.now(), text, sender: 'me', time: nowTime() };

    setDraft('');
    setMessagesByMode((current) => ({
      ...current,
      [sendingMode]: [...current[sendingMode], userMessage],
    }));
    setHistoryByMode((current) => ({ ...current, [sendingMode]: nextHistory }));
    setIsBusy(true);
    requestAnimationFrame(resizeInput);

    await sleep(520 + Math.random() * 560);
    if (mode === sendingMode) setIsTyping(true);

    try {
      const reply = await callAiWithFallback(nextHistory, sendingMode);
      await sleep(260 + Math.random() * 340);
      setIsTyping(false);

      const bursts = splitBursts(reply || 'hmm');
      for (const [index, burst] of bursts.entries()) {
        if (index > 0 && mode === sendingMode) {
          setIsTyping(true);
          await sleep(360 + Math.random() * 420);
          setIsTyping(false);
        }

        setMessagesByMode((current) => ({
          ...current,
          [sendingMode]: [
            ...current[sendingMode],
            { id: Date.now() + index + 1, text: burst, sender: 'them', time: nowTime() },
          ],
        }));
      }

      setHistoryByMode((current) => ({
        ...current,
        [sendingMode]: [...current[sendingMode], { role: 'model', parts: [{ text: reply }] }].slice(-32),
      }));
    } catch (error) {
      setIsTyping(false);
      setToast((error as Error).message.slice(0, 72) || 'Something went wrong');
    } finally {
      setIsBusy(false);
    }
  }

  function handleKeyDown(event: React.KeyboardEvent<HTMLTextAreaElement>) {
    if (event.key === 'Enter' && !event.shiftKey) {
      event.preventDefault();
      void handleSend();
    }
  }

  return (
    <main
      className={`h-dvh w-screen overflow-hidden font-[-apple-system,BlinkMacSystemFont,'SF_Pro_Text','Helvetica_Neue',Arial,sans-serif] tracking-normal ${
        isLight ? 'bg-[#d1d7db] text-[#111b21]' : 'bg-[#0b141a] text-[#e9edef]'
      }`}
    >
      <div
        className={`mx-auto flex h-full w-full max-w-[760px] flex-col shadow-2xl md:h-[96dvh] md:max-w-[430px] md:translate-y-[2dvh] md:overflow-hidden md:rounded-[28px] md:ring-1 ${
          isLight ? 'bg-[#efeae2] md:ring-black/10' : 'bg-[#0b141a] md:ring-white/10'
        }`}
      >
        <header
          className={`relative flex h-[64px] shrink-0 items-center gap-2 px-2.5 shadow-[0_1px_0_rgba(0,0,0,0.08)] ${
            isLight ? 'bg-[#008069]' : 'bg-[#202c33]'
          }`}
        >
          <button className="grid size-10 place-items-center rounded-full text-white/90 transition hover:bg-white/10" aria-label="Back">
            <ArrowLeft className="size-[22px]" strokeWidth={2.2} />
          </button>

          <img
            src={avatarFor(mode)}
            alt={activeMode.name}
            className="size-11 shrink-0 rounded-full object-cover ring-1 ring-white/15"
          />

          <button
            onClick={() => setMenuOpen((open) => !open)}
            className="flex min-w-0 flex-1 items-center gap-1.5 rounded-full py-1 pl-1 text-left transition hover:bg-white/5"
            aria-label="Switch chat mode"
          >
            <span className="truncate text-[17px] font-semibold leading-tight text-white">{activeMode.name}</span>
            <ChevronDown className={`size-4 shrink-0 text-white/75 transition ${menuOpen ? 'rotate-180' : ''}`} />
          </button>

          <div className="flex shrink-0 items-center gap-0.5 text-white/82">
            <button
              onClick={() => setIsLight((value) => !value)}
              className="grid size-10 place-items-center rounded-full transition hover:bg-white/10"
              aria-label="Toggle light mode"
            >
              {isLight ? <Moon className="size-5" strokeWidth={2.15} /> : <Sun className="size-5" strokeWidth={2.15} />}
            </button>
            <button
              onClick={() => {
                setMenuOpen(false);
                setCreditsOpen((open) => !open);
              }}
              className="grid size-10 place-items-center rounded-full transition hover:bg-white/10"
              aria-label="More options"
            >
              <MoreVertical className="size-[21px]" strokeWidth={2.15} />
            </button>
          </div>

          {menuOpen && (
            <div
              className={`absolute left-[58px] right-3 top-[58px] z-40 overflow-hidden rounded-2xl border shadow-2xl ${
                isLight ? 'border-black/10 bg-white text-[#111b21]' : 'border-white/10 bg-[#233138] text-[#e9edef]'
              }`}
            >
              {modeOptions.map(([id, cfg]) => (
                <button
                  key={id}
                  onClick={() => requestMode(id)}
                  className={`flex w-full items-center gap-3 px-3.5 py-3 text-left transition ${
                    isLight ? 'hover:bg-[#f0f2f5]' : 'hover:bg-[#182229]'
                  }`}
                >
                  <img src={avatarFor(id, 40)} alt="" className="size-10 rounded-full" />
                  <span className="min-w-0 flex-1 truncate text-[15px] font-medium">{cfg.name}</span>
                  {id === mode && <Check className="size-5 text-[#00a884]" strokeWidth={2.2} />}
                </button>
              ))}
            </div>
          )}


          {creditsOpen && (
            <div
              className={`absolute right-3 top-[58px] z-40 w-[min(330px,calc(100vw-24px))] overflow-hidden rounded-2xl border p-4 shadow-2xl ${
                isLight ? 'border-black/10 bg-white text-[#111b21]' : 'border-white/10 bg-[#233138] text-[#e9edef]'
              }`}
            >
              <div className="text-[15px] font-semibold">Credits</div>
              <div className={`mt-2 text-[13px] leading-relaxed ${isLight ? 'text-[#54656f]' : 'text-[#aebac1]'}`}>
                &copy; Made by Md Enaitul Hoque | 2026
              </div>
              <div className={`mt-3 text-[12px] font-semibold uppercase tracking-[0.08em] ${isLight ? 'text-[#667781]' : 'text-[#8696a0]'}`}>
                Technologies used
              </div>
              <div className={`mt-1.5 text-[13px] leading-relaxed ${isLight ? 'text-[#54656f]' : 'text-[#aebac1]'}`}>
                React, TypeScript, Vite, Tailwind CSS, Lucide React, and Gemini API.
              </div>
            </div>
          )}
        </header>

        <section
          ref={scrollRef}
          className={`relative flex-1 overflow-y-auto px-3 py-3 [scrollbar-width:thin] [scrollbar-color:#8696a0_transparent] ${
            isLight ? 'bg-[#efeae2]' : 'bg-[#0b141a]'
          }`}
        >
          <div
            className={`pointer-events-none absolute inset-0 ${
              isLight
                ? "opacity-[0.28] [background-image:url('data:image/svg+xml,%3Csvg_width=%2760%27_height=%2760%27_viewBox=%270_0_60_60%27_xmlns=%27http://www.w3.org/2000/svg%27%3E%3Cg_fill=%27none%27_stroke=%27667581%27_stroke-opacity=%270.4%27_stroke-width=%271%27%3E%3Cpath_d=%27M10_10h8v8h-8zM37_5l8_8-8_8-8-8zM7_42c5-9_13-9_18_0M39_37h10v10H39z%27/%3E%3C/g%3E%3C/svg%3E')]"
                : "opacity-[0.38] [background-image:url('data:image/svg+xml,%3Csvg_width=%2760%27_height=%2760%27_viewBox=%270_0_60_60%27_xmlns=%27http://www.w3.org/2000/svg%27%3E%3Cg_fill=%27none%27_stroke=%27%23e9edef%27_stroke-opacity=%270.08%27_stroke-width=%271%27%3E%3Cpath_d=%27M10_10h8v8h-8zM37_5l8_8-8_8-8-8zM7_42c5-9_13-9_18_0M39_37h10v10H39z%27/%3E%3C/g%3E%3C/svg%3E')]"
            } [background-size:190px_190px]`}
          />

          <div className="relative z-10 mx-auto flex max-w-[720px] flex-col gap-1.5">
            <div className="mb-2 mt-1 flex justify-center">
              <span
                className={`rounded-lg px-3 py-1 text-[12px] leading-none shadow-sm ${
                  isLight ? 'bg-white/85 text-[#667781]' : 'bg-[#182229]/95 text-[#8696a0]'
                }`}
              >
                Today
              </span>
            </div>

            {messages.map((message) => (
              <div
                key={message.id}
                className={`flex ${message.sender === 'me' ? 'justify-end' : 'justify-start'}`}
              >
                <article
                  className={`flex max-w-[82%] flex-col rounded-[22px] px-3.5 pb-1.5 pt-2 text-[15px] leading-[1.38] shadow-[0_1px_1px_rgba(0,0,0,0.18)] ${
                    message.sender === 'me'
                      ? isLight
                        ? 'rounded-br-[7px] bg-[#d9fdd3] text-[#111b21]'
                        : 'rounded-br-[7px] bg-[#005c4b] text-[#e9edef]'
                      : isLight
                        ? 'rounded-bl-[7px] bg-white text-[#111b21]'
                        : 'rounded-bl-[7px] bg-[#202c33] text-[#e9edef]'
                  }`}
                >
                  <span className="whitespace-pre-wrap break-words pr-1">{message.text}</span>
                  <span
                    className={`mt-0.5 flex items-center justify-end gap-1 self-end text-[11px] leading-none ${
                      message.sender === 'me'
                        ? isLight
                          ? 'text-[#667781]'
                          : 'text-[#8fc9bd]'
                        : 'text-[#8696a0]'
                    }`}
                  >
                    {message.time}
                    {message.sender === 'me' && <CheckCheck className="size-4 text-[#53bdeb]" strokeWidth={2.05} />}
                  </span>
                </article>
              </div>
            ))}

            {isTyping && (
              <div className="flex justify-start">
                <div
                  className={`flex items-center gap-1 rounded-[22px] rounded-bl-[7px] px-4 py-3 shadow-[0_1px_1px_rgba(0,0,0,0.18)] ${
                    isLight ? 'bg-white' : 'bg-[#202c33]'
                  }`}
                >
                  <span className="size-2 animate-bounce rounded-full bg-[#8696a0] [animation-delay:-220ms]" />
                  <span className="size-2 animate-bounce rounded-full bg-[#8696a0] [animation-delay:-110ms]" />
                  <span className="size-2 animate-bounce rounded-full bg-[#8696a0]" />
                </div>
              </div>
            )}
          </div>
        </section>

        <footer
          className={`grid shrink-0 grid-cols-[minmax(0,1fr)_44px] items-end gap-2 px-2.5 pt-2.5 pb-[calc(max(1rem,env(safe-area-inset-bottom))+0.875rem)] ${
            isLight ? 'bg-[#f0f2f5]' : 'bg-[#202c33]'
          }`}
        >
          <div
            className={`flex min-h-11 min-w-0 items-end gap-1 rounded-[24px] px-2 py-1.5 shadow-inner shadow-black/10 ${
              isLight ? 'bg-white' : 'bg-[#2a3942]'
            }`}
          >
            <button
              className={`grid size-8 shrink-0 place-items-center rounded-full transition ${
                isLight ? 'text-[#54656f] hover:bg-black/5' : 'text-[#aebac1] hover:bg-white/5'
              }`}
              aria-label="Emoji"
            >
              <Smile className="size-[21px]" strokeWidth={2.05} />
            </button>

            <textarea
              ref={inputRef}
              value={draft}
              onChange={(event) => {
                setDraft(event.target.value);
                requestAnimationFrame(resizeInput);
              }}
              onKeyDown={handleKeyDown}
              placeholder="Message"
              rows={1}
              className={`max-h-[118px] min-h-8 min-w-0 flex-1 resize-none self-center bg-transparent py-1.5 text-[16px] leading-[1.35] outline-none ${
                isLight ? 'text-[#111b21] placeholder:text-[#667781]' : 'text-[#e9edef] placeholder:text-[#8696a0]'
              }`}
              spellCheck
            />

            <button
              className={`grid size-8 shrink-0 place-items-center rounded-full transition ${
                isLight ? 'text-[#54656f] hover:bg-black/5' : 'text-[#aebac1] hover:bg-white/5'
              }`}
              aria-label="Attach file"
            >
              <Paperclip className="size-[21px]" strokeWidth={2.05} />
            </button>
          </div>

          <button
            onClick={() => void handleSend()}
            disabled={isBusy || !hasDraft}
            className={`grid size-11 shrink-0 place-items-center rounded-full transition ${
              hasDraft
                ? 'bg-[#00a884] text-white shadow-[0_2px_10px_rgba(0,168,132,0.35)] active:scale-95'
                : isLight
                  ? 'bg-[#d1d7db] text-[#54656f]'
                  : 'bg-[#2a3942] text-[#aebac1]'
            }`}
            aria-label="Send message"
          >
            <Send className="ml-0.5 size-5 fill-current" strokeWidth={0} />
          </button>
        </footer>
      </div>


      {gfPromptOpen && (
        <div className="fixed inset-0 z-50 grid place-items-center bg-black/55 px-5 backdrop-blur-sm">
          <div
            className={`w-full max-w-[330px] rounded-2xl border p-4 shadow-2xl ${
              isLight ? 'border-black/10 bg-white text-[#111b21]' : 'border-white/10 bg-[#233138] text-[#e9edef]'
            }`}
          >
            <div className="mb-3 text-[17px] font-semibold">Enter password</div>
            <input
              value={gfPassword}
              onChange={(event) => {
                setGfPassword(event.target.value);
                setGfError('');
              }}
              onKeyDown={(event) => {
                if (event.key === 'Enter') void unlockGfMode();
                if (event.key === 'Escape') setGfPromptOpen(false);
              }}
              type="password"
              autoFocus
              className={`h-11 w-full rounded-xl border px-3 text-[15px] outline-none ${
                isLight
                  ? 'border-black/10 bg-[#f0f2f5] text-[#111b21]'
                  : 'border-white/10 bg-[#182229] text-[#e9edef]'
              }`}
            />
            {gfError && <div className="mt-2 text-[13px] text-[#ff6b6b]">{gfError}</div>}
            <div className="mt-4 flex justify-end gap-2">
              <button
                onClick={() => setGfPromptOpen(false)}
                className={`rounded-full px-4 py-2 text-[14px] ${isLight ? 'text-[#54656f]' : 'text-[#aebac1]'}`}
              >
                Cancel
              </button>
              <button
                onClick={() => void unlockGfMode()}
                className="rounded-full bg-[#00a884] px-4 py-2 text-[14px] font-semibold text-white"
              >
                Unlock
              </button>
            </div>
          </div>
        </div>
      )}

      {toast && (
        <div className="fixed bottom-20 left-1/2 z-50 max-w-[min(88vw,360px)] -translate-x-1/2 rounded-full bg-black/80 px-4 py-2 text-center text-[13px] text-white shadow-xl backdrop-blur">
          {toast}
        </div>
      )}
    </main>
  );
}
